################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  insecure: false
################################################################
# Docker configuration backend
################################################################
providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  #docker:
  #  exposedByDefault: false
  #  watch: true
################################################################
# Traefik Logging
################################################################
log:
  level: INFO
################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
################################################################
# Challenge TLS
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: postmaster@example.com
      # Comment next line for production environment default value
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /letsencrypt/acme.json
#      tlsChallenge: true
      httpChallenge:
        # used during the challenge
        entryPoint: web